name: Sync all matching branches with upstream via PR

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

env:
  UPSTREAM_REPO: mother-of-all-self-hosting/mash-playbook

jobs:
  discover-branches:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Get upstream branches
        id: upstream
        uses: actions/github-script@v7
        with:
          script: |
            const [owner, repo] = process.env.UPSTREAM_REPO.split('/');
            let page = 1, upstream_branches = [];
            while(true) {
              const { data } = await github.rest.repos.listBranches({ owner, repo, per_page: 100, page });
              if (data.length === 0) break;
              upstream_branches = upstream_branches.concat(data.map(b => b.name));
              page++;
            }
            core.setOutput('branches', JSON.stringify(upstream_branches));

      - name: Get fork branches
        id: fork
        uses: actions/github-script@v7
        with:
          script: |
            let page = 1, fork_branches = [];
            while(true) {
              const { data } = await github.rest.repos.listBranches({
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 100,
                page
              });
              if (data.length === 0) break;
              fork_branches = fork_branches.concat(data.map(b => b.name));
              page++;
            }
            core.setOutput('branches', JSON.stringify(fork_branches));

      - name: Set matrix
        id: set-matrix
        run: |
          echo "Finding intersection of branches..."
          upstream=$(echo '${{ steps.upstream.outputs.branches }}' | jq -r '.[]')
          fork=$(echo '${{ steps.fork.outputs.branches }}' | jq -r '.[]')
          intersection=$(for u in $upstream; do for f in $fork; do [ "$u" = "$f" ] && echo "\"$u\""; done; done | jq -s .)
          echo "matrix={\"branch\":$intersection}" >> $GITHUB_OUTPUT

  sync:
    needs: discover-branches
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.discover-branches.outputs.matrix)}}
    env:
      UPSTREAM_REPO: mother-of-all-self-hosting/mash-playbook
    steps:
      - name: Checkout fork branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/${{ env.UPSTREAM_REPO }}.git

      - name: Fetch upstream branch
        run: git fetch upstream ${{ matrix.branch }}

      - name: Create or update sync branch
        run: |
          git checkout -B upstream-sync-${{ matrix.branch }}
          git reset --hard upstream/${{ matrix.branch }}
          git push -f origin upstream-sync-${{ matrix.branch }}

      - name: Find existing PR number (if any)
        id: find_pr
        uses: actions/github-script@v7
        with:
          script: |
            const branch = process.env.BRANCH || '${{ matrix.branch }}';
            const syncBranch = `upstream-sync-${branch}`;
            const { data: pulls } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${syncBranch}`,
              base: branch,
              state: 'open'
            });
            if (pulls.length > 0) {
              core.setOutput('pr_number', pulls[0].number);
            }

      - name: Create PR if needed
        id: create_pr
        uses: actions/github-script@v7
        with:
          script: |
            const branch = process.env.BRANCH || '${{ matrix.branch }}';
            const syncBranch = `upstream-sync-${branch}`;
            let pr_number = "${{ steps.find_pr.outputs.pr_number }}";
            if (!pr_number) {
              const { data: pr } = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Sync with upstream ${branch}`,
                head: syncBranch,
                base: branch,
                body: `Automated PR to merge upstream changes from \`${process.env.UPSTREAM_REPO}@${branch}\` into this fork's \`${branch}\`.`,
              });
              pr_number = pr.number;
            }
            core.setOutput('pr_number', pr_number);

      - name: Enable auto-merge on PR
        if: steps.create_pr.outputs.pr_number != ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = Number('${{ steps.create_pr.outputs.pr_number }}');
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            });
            const prNodeId = pr.node_id;
            await github.graphql(`
              mutation($pullRequestId:ID!) {
                enablePullRequestAutoMerge(input: {pullRequestId: $pullRequestId, mergeMethod: MERGE}) {
                  pullRequest {
                    autoMergeRequest {
                      enabledAt
                      enabledBy {
                        login
                      }
                    }
                  }
                }
              }
            `, {
              pullRequestId: prNodeId
            });
