name: Sync fork with upstream via PR

on:
  schedule:
    - cron: '0 1 * * *'   # Runs daily at 1 AM UTC
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

env:
  UPSTREAM_REPO: mother-of-all-self-hosting/mash-playbook

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get upstream default branch
        id: upstream_branch
        uses: actions/github-script@v7
        with:
          script: |
            const repo = process.env.UPSTREAM_REPO;
            const [owner, repoName] = repo.split('/');
            const { data } = await github.rest.repos.get({
              owner,
              repo: repoName
            });
            core.setOutput('branch', data.default_branch);

      - name: Add upstream remote
        run: git remote add upstream https://github.com/${{ env.UPSTREAM_REPO }}.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Create or update sync branch
        run: |
          git checkout -B upstream-sync
          git reset --hard upstream/${{ steps.upstream_branch.outputs.branch }}
          git push -f origin upstream-sync

      - name: Find existing PR number (if any)
        id: find_pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pulls } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:upstream-sync`,
              base: '${{ steps.upstream_branch.outputs.branch }}',
              state: 'open'
            });
            if (pulls.length > 0) {
              core.setOutput('pr_number', pulls[0].number);
            }

      - name: Create PR if needed
        id: create_pr
        uses: actions/github-script@v7
        with:
          script: |
            let pr_number = "${{ steps.find_pr.outputs.pr_number }}";
            if (!pr_number) {
              const { data: pr } = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Sync with upstream (${{ steps.upstream_branch.outputs.branch }})`,
                head: "upstream-sync",
                base: "${{ steps.upstream_branch.outputs.branch }}",
                body: `Automated PR to merge upstream changes from \`${process.env.UPSTREAM_REPO}\` into this fork.`,
              });
              pr_number = pr.number;
            }
            core.setOutput('pr_number', pr_number);

      - name: Enable auto-merge on PR
        if: steps.create_pr.outputs.pr_number != ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.pulls.enableAutoMerge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: Number('${{ steps.create_pr.outputs.pr_number }}'),
              merge_method: "merge"
            })
